module.exports={
    entry:"./src/index.tsx",
    output:{
        filename:"./app.js"
    },
    devtool:"source-map",
    resolve:{
        extensions:[".ts",".tsx",".js",".jsx"] 
    },
    module:{
        rules:[
            {test:/\.tsx?$/,loader:"ts-loader"}
        ]
    }
}